name: Deploy Integra (Manual)

on:
  workflow_dispatch:   # lets you run it manually in the Actions tab
    inputs:
      environment:
        description: 'Where to deploy?'
        required: true
        default: 'staging'
      branch:
        description: 'Branch of Integra to deploy'
        required: true
        default: 'main'

jobs:
  call-reusable:
    uses: nafberger/scripts-devops-test/.github/workflows/deploy-full.yml@pipelines
    with:
      branch: main
      webapp_name: SimpleWebFormsTest
      package_path: ./publish
      deployment_path: C:\inetpub\wwwroot\SimpleWebFormsTest
      website_port: '8080'
      app_pool_dotnet_version: v4.0
    secrets: inherit
