name: Deploy Integra (Manual)

on:
  workflow_dispatch:   # lets you run it manually in the Actions tab
    inputs:
      environment:
        description: 'Where to deploy?'
        required: true
        default: 'staging'
      branch:
        description: 'Branch of Integra to deploy'
        required: true
        default: 'main'

jobs:
  call-reusable:
    uses: your-org/pipelines-repo/.github/workflows/deploy-full.yml@pipelines
    with:
      environment: ${{ github.event.inputs.environment }}
      branch: ${{ github.event.inputs.branch }}
    secrets: inherit
